### ISSUE TITLE
Les capsules ne sont pas toujours comptées

### ISSUE THREAD

**Issue by trivetroff** [adavid1/Bob_Raoul_v2#1]
Bonjour adavid1,

Description du bug:
Parfois les capsules ne sont pas comptées alors qu'on les entend bien descendre dans le Raoul.

Reproduction du bug:
Envoyer une capsule dans le Raoul, avec une probabilité d'environ 10% elle ne sera pas comptée.

**Comment by adavid1** [comment]
Bonjour trivetroff,

Nous allons réaliser une phase de test dans le but de comptabiliser le taux de non détection factuel de certaines capsules, nous agirons en conséquence dans le but de maximiser la probabilité de détection.
